name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --frozen
        uv pip install pylint black isort

    - name: Lint with pylint
      run: |
        uv run pylint src/ --exit-zero --rcfile=.pylintrc || true

    - name: Check code formatting with black
      run: |
        uv run black --check src/ main.py || true

    - name: Check import sorting with isort
      run: |
        uv run isort --check-only src/ main.py || true

    - name: Run tests
      run: |
        uv run pytest tests/ -v --tb=short || true

    - name: Test main script (limited)
      run: |
        uv run python main.py --test --log-level DEBUG
      env:
        TRANSFORMERS_CACHE: ~/.cache/huggingface
        HF_HOME: ~/.cache/huggingface
        TOKENIZERS_PARALLELISM: false
      timeout-minutes: 10

  validate-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Install PyYAML
      run: uv pip install pyyaml

    - name: Validate config.yaml
      run: |
        uv run python -c "
        import yaml
        with open('config.yaml', 'r') as f:
            config = yaml.safe_load(f)
            assert 'general' in config, 'Missing general section'
            assert 'translation' in config, 'Missing translation section'
            assert 'summarization' in config, 'Missing summarization section'
            print('[OK] Config file is valid')
        "